### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by oleksis** [Joeriksson/django-forums-app#12]
Hello, I checked the forum application and according to the model a Post can have several threads. Can you answer a thread from the same post? that is, can a thread have another thread as its parent?

**Comment by Joeriksson** [comment]
Hi @oleksis,

A post can only belong to one thread, and a thread can belong to one forum. The post relates to a thread via its thread id as can be seen in the picture below.

<img width="820" alt="Skärmavbild 2020-03-24 kl  07 54 03" src="https://user-images.githubusercontent.com/25037079/77397047-2d951d80-6da5-11ea-877e-f6010c14b2e3.png">

**Comment by oleksis** [comment]
Thank you for sharing the Model. I would like to see Post parents and children handling

**Comment by Joeriksson** [comment]
Most of this handling can be found in the  `forums/views.py` file. I use Class Based Views which makes it a little bit simpler. But also have to use some extra context, and override form_valid sometimes.
