### ISSUE TITLE
User profiles

### ISSUE THREAD

**Issue by Joeriksson** [Joeriksson/django-forums-app#4]
There should be a model related to user for storing the users profile settings. For example a default signature that is shown when a users creates a post.

**Comment by prkhrv** [comment]
Can i Work on it?

**Comment by Joeriksson** [comment]
Hi Prakhar,

Sure, it would be nice!

I want the profile to have its own model with a one-to-one relation to the User model. So the user model just contains data related to the authentication, and won't get bloated with a growing number of fields. Something in the style of:

```
from django.db import models
from django.contrib.auth import get_user_model

class UserProfile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, )
    country = ...
    city = ...
    .
    .
```

What do you think?

**Comment by prkhrv** [comment]
Yes I think it would be Quite Clean.

**Comment by Joeriksson** [comment]
@prkhrv Just to let you know. I've 

- created a Development branch, where I initially submit new code. 
- started working on a simple notification system in there. Maybe the notifications that are set should also be seen in the user profile, with options to turn individuals off or all off?

**Comment by Joeriksson** [comment]
Initial UserProfile functionality is added in https://github.com/Joeriksson/django-forums-app/commit/62bd97280d02fb8fd06ccd743d7def6fd4b92695 (Dev branch)
